import React from 'react';
import { ShieldCheck, Clock, FileText } from 'lucide-react';

export default function AuthorBio({ 
  authorName = "SellerKit Analytics & Editorial Team",
  authorRole = "Senior E-Commerce Data Analysts & Financial Modelers",
  lastUpdated = "2026 Rate Schedule Verified",
  category = "E-Commerce Financial Analysis"
}) {
  return (
    <div className="my-8 rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-white/[0.02] p-5 sm:p-6 space-y-4 text-xs">
      {/* Top Author Row */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-white/10 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-brand-600 text-white font-bold flex items-center justify-center text-sm shadow-md shrink-0">
            SK
          </div>
          <div>
            <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white text-sm">
              <span>{authorName}</span>
              <ShieldCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" title="Verified E-E-A-T Expert" />
            </div>
            <span className="text-slate-600 dark:text-slate-400 text-[11px] block">{authorRole}</span>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2 text-[11px] text-slate-500 dark:text-slate-400">
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10">
            <Clock className="w-3.5 h-3.5 text-brand-500" />
            <span>{lastUpdated}</span>
          </span>
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10">
            <FileText className="w-3.5 h-3.5 text-amber-500" />
            <span>{category}</span>
          </span>
        </div>
      </div>

      {/* Methodology & Disclaimer Notice */}
      <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-900 dark:text-amber-300 leading-relaxed text-[11px]">
        <span className="font-bold block mb-0.5">Financial Modeling & Accuracy Disclaimer:</span>
        Calculations generated by SellerKitHub tools rely on published marketplace fee rates (Amazon Seller Central 2026, Etsy Seller Handbook, eBay Merchant Terms). Estimates are for planning purposes. Final referral fees, dimensional weight packaging charges, and taxes may vary depending on category reclassifications, peak seasonal storage surcharges, and regional carrier postal rates.
      </div>
    </div>
  );
}
