import React from 'react';
import { ShieldCheck, Clock, FileText } from 'lucide-react';
import { useI18n } from '../i18n/utils';

export const AUTHOR_TRANSLATIONS = {
  en: {
    authorName: "SellerKit Analytics & Editorial Team",
    authorRole: "Senior E-Commerce Data Analysts & Financial Modelers",
    lastUpdated: "2026 Rate Schedule Verified",
    category: "E-Commerce Financial Analysis",
    disclaimerTitle: "Financial Modeling & Accuracy Disclaimer:",
    disclaimerText: "Calculations generated by SellerKitHub tools rely on published marketplace fee rates (Amazon Seller Central 2026, Etsy Seller Handbook, eBay Merchant Terms). Estimates are for planning purposes. Final referral fees, dimensional weight packaging charges, and taxes may vary depending on category reclassifications, peak seasonal storage surcharges, and regional carrier postal rates."
  },
  es: {
    authorName: "Equipo de Análisis e Investigación de SellerKit",
    authorRole: "Especialistas Senior en Análisis Financiero y Comercio Electrónico",
    lastUpdated: "Tarifas Verificadas para 2026",
    category: "Modelado Financiero de E-Commerce",
    disclaimerTitle: "Aviso de Precisión y Modelado Financiero:",
    disclaimerText: "Los cálculos generados por las herramientas de SellerKitHub se basan en las tablas de tarifas oficiales (Amazon Seller Central 2026, Manual del Vendedor de Etsy, Condiciones de eBay). Las estimaciones son informativas. Las comisiones finales por referencia, recargos por peso volumétrico y aranceles pueden variar según la categoría del producto, recargos de temporada alta y tarifas postales de las empresas de transporte."
  },
  ja: {
    authorName: "SellerKit アナリティクス＆リサーチチーム",
    authorRole: "シニアECデータアナリスト・財務モデリングスペシャリスト",
    lastUpdated: "2026年 最新料金体系 検証済み",
    category: "EC財務・利益率モデリング",
    disclaimerTitle: "財務シミュレーションおよび精度に関する免責事項：",
    disclaimerText: "SellerKitHubの計算結果は、各モールの公式発表料率（Amazonセラーセントラル2026年規約、Etsyセラーハンドブック、eBay加盟店規約）に基づいています。本ツールの試算は事業計画の目安です。カテゴリーの再分類、ホリデー期間の保管料割増、運送会社の実寸容積重量によって実際の請求額が変動する場合があります。"
  },
  fr: {
    authorName: "Équipe d'Analyse et de Recherche SellerKit",
    authorRole: "Analystes Financiers Seniors en E-Commerce & Modélisation",
    lastUpdated: "Grille Tarifaire 2026 Vérifiée",
    category: "Modélisation Financière E-Commerce",
    disclaimerTitle: "Avertissement sur la Précision et la Modélisation Financière :",
    disclaimerText: "Les calculs générés par SellerKitHub reposent sur les grilles tarifaires officielles publiées (Amazon Seller Central 2026, Manuel du Vendeur Etsy, Conditions eBay). Ces estimations sont données à titre indicatif. Les commissions finales et suppléments de stockage saisonniers peuvent varier selon la catégorie et les transporteurs."
  },
  de: {
    authorName: "SellerKit Analyse- & Redaktionsteam",
    authorRole: "Senior E-Commerce Datenanalysten & Finanzmodellierer",
    lastUpdated: "Gebührentabelle 2026 verifiziert",
    category: "E-Commerce Finanzanalyse",
    disclaimerTitle: "Haftungsausschluss für Finanzmodellierung & Genauigkeit:",
    disclaimerText: "Die von SellerKitHub-Tools generierten Berechnungen basieren auf veröffentlichten Marktplatzgebühren (Amazon Seller Central 2026, Etsy Verkäuferhandbuch, eBay Händlerbedingungen). Schätzungen dienen Planungszwecken. Finale Gebühren, Volumengewichtszuschläge und Steuern können je nach Kategorie und Saisonzuschlägen abweichen."
  },
  pt: {
    authorName: "Equipe de Análise e Pesquisa SellerKit",
    authorRole: "Especialistas Seniores em Análise Financeira de E-Commerce",
    lastUpdated: "Tabela de Taxas 2026 Verificada",
    category: "Modelagem Financeira de E-Commerce",
    disclaimerTitle: "Aviso de Precisão e Modelagem Financeira:",
    disclaimerText: "Os cálculos gerados pelas ferramentas SellerKitHub são baseados nas tabelas de taxas oficiais publicadas (Amazon Seller Central 2026, Manual do Vendedor Etsy, Termos eBay). As estimativas servem para planejamento. As tarifas finais por categoria, sobretaxas de peso cubado e impostos podem variar conforme a região e a transportadora."
  },
  ko: {
    authorName: "SellerKit 데이터 분석 및 리서치 팀",
    authorRole: "이커머스 수석 데이터 분석가 및 재무 모델링 전문가",
    lastUpdated: "2026년 최신 수수료율 검증 완료",
    category: "이커머스 재무 수익성 모델링",
    disclaimerTitle: "재무 모델링 및 계산 정확도 안내:",
    disclaimerText: "SellerKitHub 도구에서 산출된 결과는 각 마켓플레이스의 공식 발표 수수료(2026 아마존 셀러 센트럴, 엣시 셀러 핸드북, 이베이 약관)를 기반으로 합니다. 본 시뮬레이션은 계획 수립 목적의 추정치이며, 카테고리 재분류, 성수기 보관료 할증, 택배사 부피무게 적용에 따라 실제 정산 금액과 차이가 발생할 수 있습니다."
  },
  it: {
    authorName: "Team di Analisi e Ricerca SellerKit",
    authorRole: "Analisti Dati Senior & Esperti di Modellazione Finanziaria E-Commerce",
    lastUpdated: "Tariffario 2026 Verificato",
    category: "Modellazione Finanziaria E-Commerce",
    disclaimerTitle: "Disclaimer su Accuratezza e Modellazione Finanziaria:",
    disclaimerText: "I calcoli generati dagli strumenti SellerKitHub si basano sulle tariffe ufficiali pubblicate (Amazon Seller Central 2026, Manuale del Venditore Etsy, Termini eBay). Le stime hanno scopo puramente informativo. Le commissioni definitive per categoria, le maggiorazioni per peso volumetrico e i supplementi per l'alta stagione possono variare."
  }
};

export default function AuthorBio({ 
  authorName,
  authorRole,
  lastUpdated,
  category,
  lang: propLang
}) {
  const { lang } = useI18n(propLang);
  const t = AUTHOR_TRANSLATIONS[lang] || AUTHOR_TRANSLATIONS.en;

  return (
    <div className="my-8 rounded-2xl border border-slate-200 dark:border-white/10 bg-slate-50 dark:bg-white/[0.02] p-5 sm:p-6 space-y-4 text-xs">
      {/* Top Author Row */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-white/10 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-brand-600 text-white font-bold flex items-center justify-center text-sm shadow-md shrink-0">
            SK
          </div>
          <div>
            <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-white text-sm">
              <span>{authorName || t.authorName}</span>
              <ShieldCheck className="w-4 h-4 text-emerald-600 dark:text-emerald-400" title="Verified E-E-A-T Expert" />
            </div>
            <span className="text-slate-600 dark:text-slate-400 text-[11px] block">{authorRole || t.authorRole}</span>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2 text-[11px] text-slate-500 dark:text-slate-400">
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10">
            <Clock className="w-3.5 h-3.5 text-brand-500" />
            <span>{lastUpdated || t.lastUpdated}</span>
          </span>
          <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md bg-white dark:bg-white/5 border border-slate-200 dark:border-white/10">
            <FileText className="w-3.5 h-3.5 text-amber-500" />
            <span>{category || t.category}</span>
          </span>
        </div>
      </div>

      {/* Methodology & Disclaimer Notice */}
      <div className="p-3.5 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-900 dark:text-amber-300 leading-relaxed text-[11px]">
        <span className="font-bold block mb-0.5">{t.disclaimerTitle}</span>
        {t.disclaimerText}
      </div>
    </div>
  );
}
